name: publish

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: |
          sudo apt-get update 
          sudo apt-get install -y ssh

      - name: Set up SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MY_PEM_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          MY_PEM_KEY: ${{ secrets.MY_PEM_KEY }}

      - name: Deploy to vm of azure
        env:
            SSH_PASS: ${{ secrets.MY_PEM_KEY }}
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          sudo ssh -t -o "StrictHostKeyChecking=no" -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST << 'EOF'
            cd appRepo/RESTful-API/
            git pull origin main
            sudo docker compose up -d --build
          EOF