name: publish

on:
  pull_request:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to vm of azure
        run: 
          sudo sshpass -p "${{ secrets.MY_PEM_KEY }}" ssh -o StrictHostKeyChecking=no ${{ secrets.AUTH_SERVER }} << 'EOF'
            cd /appRepo/RESTful-API
            git pull origin main
            sudo docker compose up --build
          EOF