name: publish

on:
  pull_request:
    branches:
      - main

jobs:

  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker compose up --build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - name: Push Docker image
        run:
          docker compose up --build . --tag ghcr.io/andres7854/toDoAPI:latest
          docker push ghcr.io/andres7854/toDoAPI:latest

    deploy:
      needs: create-docker-image
      runs-on: ubuntu-latest
      steps:
        - name: Install sshpass
          run: sudo apt-get install sshpass

        - name: Deploy to vm of azure
          run: 
            sshpass -p ${{ secrets.MY_PEM_KEY }} ssh -o StrictHostKeyChecking=no ${{secrets.AUTH_SERVER}} << EOF
              cd /home/andres/toDoAPI
              docker login ghcr.io -u andres7854 -p ${{ secrets.CONTAINER_REGISTRY_TOKEN }}  
              docker pull ghcr.io/andres7854/toDoAPI:latest
              docker stop toDoAPI
              docker compose up --build
            EOF