name: publish

on:
  pull_request:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Deploy to vm of azure
        run: 
          sudo sshpass -p ${{ secrets.MY_PEM_KEY }} ssh ${{secrets.AUTH_SERVER}} << EOF
            cd /appRepo/RESTful-API
            git pull origin main
            sudo docker compose up --build
          EOF