name: publish

on:
  pull_request:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Deploy to vm of azure
        run: 
          sudo ssh -o "StrictHostKeyChecking=no" -i ${{ secrets.AUTH_SERVER }} << EOF
            cd /appRepo/RESTful-API
            git pull origin main
            sudo docker compose up --build
          EOF